### PR TITLE
Fixes Issue #40

### LINKED ISSUE #40: RpcClient Queues do not delete when expected
When RpcClients publish multiple requests the temp queues used the receive the responses from the RpcServer do not get cleaned up immediately. You can observe queue count balloon if you create a long running script that throws off many requests. The queues need to be deleted immediately after use.

### PR DESCRIPTION
**Pull request by shamil614**
Fixes #40

* Deletes Queues immediately after the last consumer is unsubscribed
* Reduces memory load

### CODE REVIEW

File: lib/carrot_rpc/rpc_client.rb [hunk 1]
```diff
@@ -49,7 +49,7 @@ def start
   def subscribe
     # Empty queue name ends up creating a randomly named queue by RabbitMQ
     # Exclusive => queue will be deleted when connection closes. Allows for automatic "cleanup".
-    @reply_queue = @channel.queue("", exclusive: true)
+    @reply_queue = @channel.queue("", exclusive: true, auto_delete: true, durable: false)
```
Comment (KronicDeth) [inline lib/carrot_rpc/rpc_client.rb]: I'd prefer the options to be in alphabetical order, so it's easier to visually scan which ones we are using.

Comment (shamil614) [inline lib/carrot_rpc/rpc_client.rb]: That's nice but not worth a change.
